### ISSUE TITLE
Dev: ICPC frozen ranking checklist

### ISSUE THREAD

**Issue by leduythuccs** [VNOI-Admin/OJ#214]
Here is a list of features that we need to implement before launching a testing ICPC contest:

- [x] Show frozen ranking (added in #212)
- [x] Cache ranking (the ranking page will have a lot of traffic)
- [x] Highlight first solved (added in #211)
- [ ] TBD

**Comment by leduythuccs** [comment]
All done.
